### PR TITLE
Not throwing when re-initializing parse, and some build tools changes so it builds as a submodule

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by toddgardner** [comment]
Not a big fan of mutable global state; it might be better to track down why it's being initialized multiple times (especially if upstream doesn't take this patch) or log and do nothing.

**Comment by ghost** [comment]
we re-initialize it to set the new parse appId and clientKey if the backend returns one. According to parse this is against their sdk design - they throw an exception when we try to re-initialize.

**Comment by toddgardner** [comment]
The problem is the rest of the code might not respect your mutation. Some poking around found things like:

https://github.com/ParsePlatform/Parse-SDK-Android/blob/bdd5f50d51d30030b9df12c0e09d08d8859e64be/Parse/src/main/java/com/parse/ParseCorePlugins.java#L83

Which won't respect a mutable change to ParsePlugins; it caches the global state which it assumes immutable in it's own global state

**Comment by toddgardner** [comment]
(which is to say I don't have a great answer for this, other than haranguing upstream)

**Comment by ghost** [comment]
I see.. we could mutate the other globals ourselves? I know @jimspeth spoke to Parse about this here https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/625#issuecomment-162104214

**Comment by jimspeth** [comment]
Yeah, they basically said our use case is not supported.  Does everything work with this change?  I've been looking for a way in the iOS SDK just add a "reset everything" that would nuke all their singletons and let us re-initialize from a clean state, but it's not trivial.

**Comment by toddgardner** [comment]
It looks like doing:

``` java
ParseCorePlugins.getInstance().reset();
ParsePlugins.reset();
```

Might be sufficient (though of course runs the risk of breaking on every upgrade). I don't see anyone caching ParseCorePlugins instance.

**Comment by ghost** [comment]
great, it works

**Pull request merged**
